version: '2'

services:
  spark-master:
    image: bde2020/spark-master:2.1.1-hadoop2.7
    container_name: spark-master
    ports:
    - "8080:8080"
    - "7077:7077"
    environment:
    - "constraint:node==spark-master"
    volumes:
    - ../data:/data
    - ../target/scala-2.11/:/jobs/
    - ../conf/:/conf/
    cpuset: "0"
    mem_limit: 1g
  spark-worker-1:
    image: bde2020/spark-worker:2.1.1-hadoop2.7
    container_name: spark-worker-1
    depends_on:
    - spark-master
    ports:
    - "8081:8081"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==spark-master"
    volumes:
    - ../data:/data
    - ../target/scala-2.11/:/jobs/
    - ../conf/:/conf/
    cpuset: "1"
    mem_limit: 1g
  spark-worker-2:
    image: bde2020/spark-worker:2.1.1-hadoop2.7
    container_name: spark-worker-2
    depends_on:
    - spark-master
    ports:
    - "8082:8082"
    environment:
    - "SPARK_MASTER=spark://spark-master:7077"
    - "constraint:node==spark-worker-1"
    volumes:
    - ../data:/data
    - ../target/scala-2.11/:/jobs/
    - ../conf/:/conf/
    cpuset: "1"
    mem_limit: 1g
